Pytorch helper
scaleoutsystems/fedn pull request #135
Opened 2021-01-29 12:07 UTC by mattiasakesson

## Status

- [x] Ready
- [ ] Draft
- [ ] Hold

## Description

Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.

## Types of changes

What types of changes does your code introduce to FEDn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [x] New feature
- [ ] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [x] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [x] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/fedn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included tests to complement my changes
- [x] I have updated the related documentation (if necessary) 
- [x] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request

## Further comments

Anything else you think we should know before merging your code!

2021-02-05 23:56 UTC, morganekmefjord approved these changes

2021-02-07 19:29 UTC, ahellander requested changes

2021-02-07 19:29 UTC, ahellander commented on fedn/fedn/utils/helpers.py
> +        from fedn.utils.pytorchmodel import PytorchModelHelper
Please rename the helper to "PyTorchHelper", and helper_type to "pytorch".

2021-02-07 19:29 UTC, ahellander commented on fedn/fedn/utils/helpers.py
> +        from fedn.utils.pytorchmodel import PytorchModelHelper
Will do the same with Keras in another PR soon.

2021-02-07 19:29 UTC, ahellander commented on fedn/fedn/utils/pytorchmodel.py
>  import os
Please rename file to "pytorchhelper.py"

2021-02-07 19:29 UTC, ahellander commented on fedn/fedn/utils/pytorchmodel.py
>  import torch
torch is not needed right? If so we need to discuss, since we have removed ML-library dependencies in combiner and reducer.

2021-02-07 19:29 UTC, ahellander commented on test/pytorch_mnist/client/init_model.py
> +	torch.save(model.state_dict(), outfile_name)
You should use the helper to serialize the model, right?

2021-02-07 19:29 UTC, ahellander commented on test/pytorch_mnist/combiner/run.sh
> +#!/bin/bash
Please remove this file, not used.

2021-02-07 19:29 UTC, ahellander commented on test/pytorch_mnist/combiner/run.sh
> +fedn run fedavg -d discovery -p 8080 -t e9a3cb4c5eaff546eec33ff68a7fbe232b68a192 -h combiner -i 12080 -n combiner
Please ask Morgan for help how to remove the git-lfs files, and instead provide detailed instructions for how to obtain the files and where to stage them in the example dir, in the example readme.

2021-02-07 19:29 UTC, ahellander commented on test/pytorch_mnist/requirements.txt
> +tensorflow==2.3.2
Why is tensorflow needed?

2021-02-11 09:05 UTC, mattiasakesson commented
> Will this work for non-envidia-enabled systems ?

Not sure.

2021-02-11 13:32 UTC, ahellander approved these changes

2021-02-11 13:33 UTC, merged