Update README.md
scaleoutsystems/fedn pull request #303
Opened 2021-11-05 12:48 UTC by mattiasakesson

username and password comments for base-services

## Status

- [x] Ready
- [ ] Draft
- [ ] Hold

## Description

Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.

## Types of changes

What types of changes does your code introduce to FEDn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [ ] New feature
- [ x] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [ x] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [x ] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/fedn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included tests to complement my changes
- [ ] I have updated the related documentation (if necessary) 
- [ ] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request

## Further comments

Anything else you think we should know before merging your code!

2021-11-08 11:03 UTC, Wrede approved these changes

2021-11-08 13:57 UTC, ahellander requested changes

2021-11-08 13:57 UTC, ahellander commented on README.md
> +(You can update uername and password for the services in config/base-services.yaml, default values: user=fedn_admin, password=password)
uername -> username

2021-11-16 09:35 UTC, Wrede approved these changes

2021-11-16 09:49 UTC, ahellander approved these changes

2021-11-16 09:49 UTC, merged