Verify client and combiner token at reducer
scaleoutsystems/fedn pull request #338
Opened 2022-01-13 18:37 UTC by Wrede

## Status

- [ ] Ready
- [x] Draft
- [ ] Hold

## Description
Make use of tokens being sent in request (header). Will only check against a single token.  

## Types of changes

What types of changes does your code introduce to FEDn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [x] New feature
- [ ] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [x] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [ ] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/fedn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included tests to complement my changes
- [ ] I have updated the related documentation (if necessary) 
- [ ] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request

## Further comments

Anything else you think we should know before merging your code!

2022-01-13 18:48 UTC, ahellander requested changes
Looks solid, just a minor comment.

2022-01-13 18:48 UTC, ahellander commented on fedn/fedn/clients/reducer/restservice.py
> +            print("Authorization accepted via token", flush=True)
Don't print on success.

2022-01-19 20:29 UTC, ahellander requested changes
Great work! 

When a combiner tries to connect with an invalid token, it still stays in the retry loop, but there is no way to recover from this error without exiting and setting the correct token. So the combiner should exit when this happens. 

Same for the client.

2022-01-20 12:43 UTC, Wrede commented
> 

Done!

2022-01-21 09:03 UTC, ahellander approved these changes

2022-01-21 09:03 UTC, merged