Feature/SK-481 | Add option to delete intermediate models from disk
scaleoutsystems/fedn pull request #467
Opened 2023-05-29 10:24 UTC by Wrede

This is to avoid storage overflow on combiner and reducer disk when TempModelStorage (default) is used. Still a volume should be mounted to the folder where models are stored on disk. 

The design:
Deletion on the fly (round)
- after a single aggregation of a client model update, delete the client model from combiner storage/disk
- after reducer has downloaded a combined model from combiner storage/disk, delete the combined model (not implemented yet)
- On validation, wait for all clients validation response then delete the validation model from storage/disk. Obs that the last validation model will still be present and not deleted. This is just how the logic is implemented, but it also means that the combiner does not have to download the latest global model if a new session is started.

A POST parameter "delete_models" which should be a boolean has been added to /control in rest-api. Templates has not been updated to include a setting for this.

2023-06-08 11:54 UTC, ahellander commented on fedn/fedn/network/controller/controlbase.py
>              print("CONTROL: Deleting temporary model file...", flush=True)
Maybe remove this printout.

2023-06-08 19:07 UTC, ahellander requested changes
Looks good, just a few minor comments.

2023-06-09 08:03 UTC, Wrede commented on fedn/fedn/network/combiner/aggregators/fedavg.py
> +                        "AGGREGATOR({}): Deleted model update {} from storage.".format(self.name, model_id))
> Is this printout/logging necessary?

it's just a printout not sent to tracer sp why not?

2023-06-09 08:04 UTC, Wrede commented on fedn/fedn/network/combiner/round.py
> +                                print("ROUNDCONTROL: Deleting model {} from storage".format(
> I think we can remove this printout.

why? I would say change it to use server.report_status?

2023-06-09 14:32 UTC, ahellander commented on fedn/fedn/network/combiner/round.py
> +                                print("ROUNDCONTROL: Deleting model {} from storage".format(
Yes, let's do that.

2023-06-09 14:34 UTC, ahellander commented on fedn/fedn/network/combiner/aggregators/fedavg.py
> +                        "AGGREGATOR({}): Deleted model update {} from storage.".format(self.name, model_id))
Just to manage the amount of stuff we print to stdout. Maybe not the most useful information. But I guess the proper thing is to set log levels.

2023-06-11 20:06 UTC, ahellander approved these changes

2023-06-11 20:39 UTC, merged