fed prox example
scaleoutsystems/fedn pull request #564
Opened 2024-04-04 15:04 UTC by mattiasakesson

## Description

2024-04-07 21:33 UTC, ahellander requested changes
Looks clean and neat. Would it be possible to have a notebook or script that runs vanilla fedavg and fedprox?  I guess we would gave to have some significant degree of heterogeneity to have prox show an advnatage?

2024-04-07 21:33 UTC, ahellander commented on examples/mnist-pytorch-fedprox/client/entrypoint
> +            #print("proximal_term: ", proximal_term)
Clean up comments

2024-04-09 16:37 UTC, mattiasakesson commented
Updated.
I didnt add a notbok instead a wrote some lines in the readme about how to use fedprox and how to turn the example to vanilla fedavg by setting mu=0. I dont think a notebok will make it any clearer, you still have to manually modify the client_settings.yaml file to change the mu parameter.

2024-04-11 19:54 UTC, ahellander commented
Will it / how will it work with client_settings.yaml in the base directory and not in  the 'client' folder? 

Also, we need to rework to align with the new model incoming from the "python_env" PR.

2024-04-18 21:16 UTC, ahellander commented
Given the release with the python_env support, this one needs to be updated to the new client structure.

2024-10-10 17:07 UTC, ahellander commented
@mattiasakesson lets get the fedprox example finished, I think it is good to show how it can work.

2024-10-11 11:42 UTC, Wrede commented
Will close due to inactivity, can be re-open at later stage.

2024-10-11 11:42 UTC, closed without merging