Feature/SK-707 | Add config support to flower adapter
scaleoutsystems/fedn pull request #570
Opened 2024-04-09 11:15 UTC by viktorvaladi

Adds built-in config support to the flower adapter, for flower clients which use that.

2024-04-11 19:55 UTC, ahellander commented on examples/flower-client/client/python_env.yaml
> +  - fedn==0.8.0
Should be 0.9.0 when we release.

2024-04-11 19:56 UTC, ahellander approved these changes
Looks good. See comment about FEDn-version.

2024-04-12 06:49 UTC, Wrede commented
I suggest that you also replace the build scripts with "fedn package create" and "fedn run build".  Maybe remove ENTRTPOINT_OPS since they are confusing.

2024-04-12 12:50 UTC, Wrede requested changes

2024-04-12 12:50 UTC, Wrede commented on examples/flower-client/README.rst
> +   cd fedn/examples/mnist-pytorch
flower-client

2024-04-12 14:00 UTC, Wrede approved these changes

2024-04-12 14:08 UTC, merged