Highlighting the difference between client node and training client.
scaleoutsystems/fedn pull request #583
Opened 2024-04-18 16:47 UTC by sztoor

## Description

2024-04-23 08:16 UTC, Wrede requested changes

2024-04-23 08:16 UTC, Wrede commented on docs/quickstart.rst
> +Client node: A physical or virtual machine (MacOSx Linux or Windows) used to perform initial steps.
this just makes it more complex for the user I think, Also, it sound to much "hadoop"

2024-04-23 08:16 UTC, Wrede commented on docs/quickstart.rst
> +Initialize FEDn with the compute package and seed model
We want to move away from calling it compute package and instead refer to is as a FEDn project which can be bundled into a package which then can be used by the fedn package manager.

2024-04-23 08:16 UTC, Wrede commented on docs/quickstart.rst
> +[!NOTE] The preparation of the compute package and seed model is a one-time requirement. All training clients use the same compute package and seed model.
remove compute

2024-04-23 08:16 UTC, Wrede commented on docs/quickstart.rst
> +In order to train a federated model using FEDn, your Studio project needs to be initialized with a compute package and a seed model. The compute package is a bundle of the client specification, and t
remove compute

2024-09-02 12:07 UTC, ahellander commented
I think this has been superseeded with some of our more recent updates.

2024-09-02 12:07 UTC, closed without merging