Feature/SK-805 | FEDn cli - new order
scaleoutsystems/fedn pull request #593
Opened 2024-04-26 13:46 UTC by niklastheman

# Some changes to the CLI

- **fedn run combiner** -> **fedn combiner start**
- **fedn run client** -> **fedn client start**
- **fedn client/combiner/model/package/round/session/status/validation list** - list objects from statestore
- **refactoring** - refactored code into separate files
- **fedn config** - lists env:s (and values) relevant for the cli

2024-04-27 05:36 UTC, ahellander approved these changes
It looks right to me. I think you will have some conflicts when you merge in master though, so need to check that. 

I think it would be good if the "config" commmand also has one for actually configuring. I.e. prompt user for key configurations. But that could be a separate PR perhaps.

2024-04-27 05:36 UTC, ahellander commented on docs/faq.rst
> +Q: Can I skip fetching the remote package and instead use a local folder when developing the compute package
I think I removed this Q in current  master (since --remote False flag currently not working)

2024-04-29 07:44 UTC, niklastheman commented
> It looks right to me. I think you will have some conflicts when you merge in master though, so need to check that.
> 
> I think it would be good if the "config" commmand also has one for actually configuring. I.e. prompt user for key configurations. But that could be a separate PR perhaps.

- Merged
- I actually tried creating a command to set the env:s interactivity but found no way to make it work. The best solution I found was to prompt the user and the return the strings to paste in to a terminal. This felt sub optimal though so left it out. If you want it I can easily re-implement it.

2024-04-30 08:29 UTC, Wrede requested changes
Looks nice! Just think we should add a "obsolete" warning or error to the old "fedn run client/combiner", since this is a major change and will break many container images. Best would be to actually allow  "run client/combiner" for a while and instead pass all arguments to the new click command, that way we can have a warning between two major releases, and then in the future update to am error.

2024-05-07 07:39 UTC, niklastheman commented
> Looks nice! Just think we should add a "obsolete" warning or error to the old "fedn run client/combiner", since this is a major change and will break many container images. Best would be to actually allow "run client/combiner" for a while and instead pass all arguments to the new click command, that way we can have a warning between two major releases, and then in the future update to am error.

deprecation warning added

2024-05-07 07:44 UTC, Wrede approved these changes
Hold?

2024-05-07 08:12 UTC, niklastheman commented
> Hold?

Sure! 👌 Can be merged prior to next release.

2024-05-07 08:37 UTC, merged