Feature/SK-823 | Hugging Face Example
scaleoutsystems/fedn pull request #600
Opened 2024-05-07 12:44 UTC by FrankJonasmoelle

FEDn example that uses the Hugging Face Transformer library

2024-05-07 12:55 UTC, Wrede requested changes

2024-05-07 12:55 UTC, Wrede commented on examples/huggingface/README.rst
> +   fedn run client -in client.yaml --secure=True --force-ssl
use "fedn client start" instead

2024-05-07 12:55 UTC, Wrede commented on examples/huggingface/README.rst
> +   ghcr.io/scaleoutsystems/fedn/fedn:0.9.0 run client -in client.yaml --secure=True --force-ssl
"client start"

2024-05-07 12:55 UTC, Wrede commented on examples/huggingface/docker-compose.override.yaml
> +      FEDN_DATA_PATH: /app/package/data/clients/1/enron_spam.pt
think it should be /app/package/client/data... with recent changes comming from master

2024-05-07 12:55 UTC, Wrede commented on examples/huggingface/docker-compose.override.yaml
> +      FEDN_DATA_PATH: /app/package/data/clients/2/enron_spam.pt
/app/package/client/data

2024-05-17 12:31 UTC, ahellander approved these changes

2024-05-17 12:33 UTC, Wrede approved these changes

2024-05-17 12:34 UTC, merged