add example
scaleoutsystems/fedn pull request #703
Opened 2024-09-17 13:09 UTC by KatHellg

## Description

New example to stack. Defect detection use case for manufacturing using YOLOv8n model. 

Link to JIRA --> https://scaleoutsystems.atlassian.net/browse/SK-971?atlOrigin=eyJpIjoiMzQ0NWJhNDA0NTU2NGUyY2E2MzliNzBlZmUyZTk0NTUiLCJwIjoiaiJ9

2024-09-21 11:04 UTC, KatHellg commented
Left to do:

- add content to readme
- fix bugs in data.py file
- rm some hyperparameters in train.py

2024-09-27 11:30 UTC, Wrede commented on examples/welding-defect-detection/README.md
> +-  `Python >=3.8, <=3.12 <https://www.python.org/downloads>`__
Have it been tested with these versions?

2024-09-27 11:32 UTC, Wrede commented on examples/welding-defect-detection/README.md
> +To learn how to set up your FEDn Studio project and connect clients, take the quickstart tutorial: https://fedn.readthedocs.io/en/stable/quickstart.html. When activating the first client, you will be
I would upload the dataset to scaleout-public bucket instead, so that we are in control of the data. But this is good for now.

2024-09-27 11:34 UTC, Wrede commented on examples/welding-defect-detection/README.md
> +Below are a few examples of experiments which have been run using this example. A centralized setup has been used as baseline to compare the federated setup to. Two clients have been used in the fede
"A centralized setup has been used as baseline to compare against.

2024-09-27 11:38 UTC, Wrede commented on examples/welding-defect-detection/client/python_env.yaml
> +dependencies:
look at other examples from main branch, use the same environment markers.

2024-09-27 11:38 UTC, Wrede commented on examples/welding-defect-detection/client/python_env.yaml
> +  - torchvision==0.18.1
why torchvision? Where is it used?

2024-09-27 11:41 UTC, Wrede requested changes
Good job! I have not tested to run it but I trust it works, just test for different python versions.

2024-10-01 07:50 UTC, stefanhellander commented
I think that we should consider having a separate repository for this example, since it uses a library (Ultralytics) with an AGPL-license (can make some users nervous, even if it is not used in FEDn itself).

2024-10-11 13:11 UTC, Wrede approved these changes

2024-10-11 13:11 UTC, merged