session_id flag added
scaleoutsystems/fedn pull request #742
Opened 2024-11-08 15:32 UTC by KatHellg

added session_id flag in model_cmd.py, round_cmd.py, statuses_cmd.py, and validation_cmd.py. Works well but might be a brute force solution so please lmk if there's a smarter way of doing it.

also added an id flag in each file to be able to search based on id (e.g., model_id in model_cmd.py)

2024-11-12 08:06 UTC, niklastheman requested changes
Cool, I think I would like to have the "id functionality" (list_clients for example) refactored in separate functions (not part of list). The implementation of this looks good! The "session_id functionality" can be implemented in an other way. The GET [entity]/ endpoints accepts url params for filtering. For example: GET /rounds?session_id=<session_id_value>

2024-11-13 14:25 UTC, niklastheman requested changes
Cool, good work! I have some comments, minor things...

2024-11-13 14:25 UTC, niklastheman commented on fedn/cli/client_cmd.py
> +def get_client(ctx, protocol: str, host: str, port: str, token: str = None, id: str = None):
Think id should be required...

2024-11-13 14:25 UTC, niklastheman commented on fedn/cli/model_cmd.py
> +        headers["session_id"] = session_id
This header should not be needed.

2024-11-13 14:25 UTC, niklastheman commented on fedn/cli/package_cmd.py
> +    click.echo(f"\nretrieving package: {url}\n")
retrieving => Retrieving? :)

2024-11-13 14:25 UTC, niklastheman commented on fedn/cli/client_cmd.py
>          headers["id"] = id
This header should not be needed.

2024-11-15 09:37 UTC, Wrede commented on fedn/cli/client_cmd.py
> +    click.echo(f"Headers: {headers}")
remove print of hearder

2024-11-15 09:46 UTC, Wrede commented on fedn/cli/client_cmd.py
>      except requests.exceptions.ConnectionError:
We should handle more than just ConnectionError, there are plenty of other error related to http requests. You don't have do do this know but make an other issue of it. For example create a utility function that handles all requests and checks the response for error:


import requests
from requests.exceptions import HTTPError, Timeout, ConnectionError, RequestException

def make_request(method, url, **kwargs):
    """
    A reusable function to handle HTTP(S) requests with error handling.

    Args:
        method (str): HTTP method (e.g., 'GET', 'POST').
        url (str): The URL for the request.
        **kwargs: Additional arguments passed to `requests.request()`.

    Returns:
        dict: A dictionary with the response data or an error message.
    """
    try:
        response = requests.request(method, url, **kwargs)
        response.raise_for_status()
        # Assuming JSON response, adjust if needed
        return {"success": True, "data": response.json()}
    except HTTPError as http_err:
        return {"success": False, "error": f"HTTP error occurred: {http_err}"}
    except Timeout:
        return {"success": False, "error": "The request timed out"}
    except ConnectionError:
        return {"success": False, "error": "Connection error occurred"}
    except RequestException as req_err:
        return {"success": False, "error": f"Request error: {req_err}"}
    except Exception as e:
        return {"success": False, "error": f"Unexpected error: {e}"}

2024-11-15 09:49 UTC, Wrede commented on fedn/cli/combiner_cmd.py
> +    click.echo(f"Headers: {headers}")
remove

2024-11-15 09:51 UTC, Wrede commented on fedn/cli/model_cmd.py
> +    click.echo(f"Headers: {headers}")
remove

2024-11-15 09:53 UTC, Wrede commented on fedn/cli/shared.py
> +        desriptions: single output format (y/n)
remove (y/n)

2024-11-15 10:00 UTC, Wrede commented on fedn/cli/shared.py
> +            count, result = json_data.values()
we should consider using json pretty prints instead, however I would prefer not introducing a new dependency. Save for other issue

2024-11-15 10:03 UTC, Wrede requested changes
Good! Just remove all headers prints, I don't know why we have them, more as a debug print it feels. Had some comments that you can make new issues from. Finally, you should add unittests for cli cmds to make sure they work as expected.

2024-11-20 16:11 UTC, Wrede approved these changes

2024-11-20 16:16 UTC, niklastheman approved these changes

2024-11-20 16:19 UTC, merged