Feature/SK-1217 | Add client settings to client v2
scaleoutsystems/fedn pull request #754
Opened 2024-11-18 14:09 UTC by viktorvaladi

Adds client settings to client v2 so that the UDF code is functional.

2024-11-19 10:52 UTC, Wrede approved these changes
Add @benjaminastrand and @niklastheman as reviewer also I want 1 approval from them.

2024-11-20 16:56 UTC, benjaminastrand requested changes
Since client_options is saved inside `_process_training_request` in client_v2.py, it will only be saved if the user chooses to start the client through `fedn client start`.

I suggest saving the metadata in `update_local_model` in fedn_client.py instead.

2024-11-21 12:08 UTC, viktorvaladi commented
> Since client_options is saved inside `_process_training_request` in client_v2.py, it will only be saved if the user chooses to start the client through `fedn client start`.
> 
> I suggest saving the client_options in `update_local_model` in fedn_client.py instead.

As discussed on discord, its good to have it as it is in the PR? So for the on_train() function it would be the client_settings parameter added which defaults to an empty dict if its not used?

2024-11-22 08:03 UTC, benjaminastrand approved these changes

2024-11-22 08:51 UTC, merged