Feature/sk 1257 | Bugfixes and improvements of combiner, and new load test
scaleoutsystems/fedn pull request #774
Opened 2024-12-16 13:59 UTC by ahellander

## Description

Implements a new load test based on reading, writing and sending numpy arrays. Resolves bugs; 

- Files are not deleted as the should in FedOpt 
- Improves error handling in FedOpt
- Adds some missing time measurements in combiner
- Fixes the issue that fedn.yaml must contain python_env

2025-01-08 14:20 UTC, Wrede requested changes

2025-01-15 15:54 UTC, Wrede requested changes
need some fixes

2025-01-15 15:54 UTC, Wrede commented on fedn/network/clients/fedn_client.py
> +            # return False
remove comment

2025-01-15 15:54 UTC, Wrede commented on fedn/network/clients/fedn_client.py
> +        print("FETCH_MODEL: ", fetch_model_time)
use logger for printing

2025-01-15 15:54 UTC, Wrede commented on fedn/network/clients/fedn_client.py
> +        print("UPLOAD_MODEL ", meta["upload_model"])
use logger for printing

2025-01-15 15:54 UTC, Wrede commented on fedn/network/clients/grpc_handler.py
> +            # logger.info("Sending heartbeat to combiner")
remove comments

2025-01-15 15:54 UTC, Wrede commented on fedn/network/clients/grpc_handler.py
> +                # logger.info("Heartbeat successful.")
remove comments

2025-03-24 19:00 UTC, ahellander commented on fedn/network/clients/fedn_client.py
> +            # return False
Fixed.

2025-03-24 19:00 UTC, ahellander commented on fedn/network/clients/fedn_client.py
> +        print("FETCH_MODEL: ", fetch_model_time)
Fixed.

2025-03-24 19:02 UTC, ahellander commented on fedn/network/clients/fedn_client.py
> +        print("UPLOAD_MODEL ", meta["upload_model"])
Fixed.

2025-03-24 19:03 UTC, ahellander commented on fedn/network/clients/grpc_handler.py
> +                # logger.info("Heartbeat successful.")
Fixed.

2025-03-26 10:18 UTC, ahellander commented on fedn/network/clients/grpc_handler.py
> +            # logger.info("Sending heartbeat to combiner")
Fixed.

2025-03-26 15:17 UTC, merged