Feature/SK-1261 | Split Learning in FEDn
scaleoutsystems/fedn pull request #776
Opened 2024-12-19 14:59 UTC by FrankJonasmoelle

**This is a first implementation of Split Learning (for vertical federated learning) in FEDn.**

The implementation includes:
- A new session "splitlearning_session", which can be executed from the API client via "start_splitlearning_session"
- A new helper (splitlearninghelper) responsible for saving & loading embeddings and gradients
- A new aggregator (splitlearningagg) that concatenates client embeddings, continues the forward pass and calculates gradients based on the labels it receives
- The logic is based on a **forward** and **backward** pass
- In the forward pass, clients generate embeddings and send them to a combiner, where they are concatenated and the gradients are calculated
- In the backward pass, the calculated gradients are sent back to the clients, who update their model parameters by continuing the backward pass
- A vertical federated learning example, based on the titanic data set, for demonstration.

Limitations:
- The current implementation works for only one combiner
- It is assumed that the data & labels are sorted by index
- Training data is processed in one batch

2025-04-03 09:00 UTC, Wrede requested changes
impressive, however I wonder if you could implement the agg using server-functions instead? This because of the dep on torch, same for helper but we currently don't have a way to user-define helper except from source. Also the PR is up do date with master? Make sure the new DTOs work.

2025-04-03 09:17 UTC, FrankJonasmoelle commented on examples/splitlearning_diabetes/data/diabetes.csv
It's 24 KB, uploaded it for convenience

2025-04-11 13:40 UTC, FrankJonasmoelle commented on fedn/network/api/client.py
> +    def start_splitlearning_session(
The logical difference is that a normal session requires a seed model, whereas this is not the case for a splitlearning session. The check for an initial seed model in "session_routes.py" is removed for splitlearning sessions. Of course, one could combine it to one function if preferred.

2025-04-22 11:30 UTC, Wrede reviewed
Status on this @FrankJonasmoelle ?

2025-04-23 07:54 UTC, FrankJonasmoelle commented on fedn/network/combiner/aggregators/splitlearningagg.py
Server-functions also do not allow torch as a dependency. Let's discuss this

2025-04-28 14:28 UTC, FrankJonasmoelle commented on fedn/network/combiner/roundhandler.py
> +        self.update_handler.waitforit(config, buffer_size=buffer_size)
Changed it and set it so that it always waits for all clients. It is enforced that all clients need to send embeddings, otherwise the algorithm does not make sense. As SL would only be used with a low number of clients (cross-silo setting), this should be ok.

2025-04-28 14:28 UTC, FrankJonasmoelle commented on fedn/network/grpc/fedn_pb2.py
> +# Protobuf Python Version: 5.27.2
Changed it to the exact protobuf version (5.28.1)

2025-04-28 14:28 UTC, FrankJonasmoelle commented on fedn/utils/helpers/plugins/splitlearninghelper.py
> +import torch
removed this one

2025-05-09 14:40 UTC, Wrede approved these changes

2025-05-09 14:43 UTC, merged